s = set()
n = input("Enter a number 1: ")
s.add(n)
n = input("Enter a number 2: ")
s.add(n)
n = input("Enter a number 3: ")
s.add(n)
n = input("Enter a number 4: ")
s.add(n)
n = input("Enter a number 5: ")
s.add(n)
n = input("Enter a number 6: ")
s.add(n)
n = input("Enter a number 7: ")
s.add(n)
n = input("Enter a number 8: ")
s.add(n)

print(s)