print("Escape Sequences in Python:")
print("---------------------------")
print("New Line: \n")
print("Tab: \t")
print("Backslash: \\")
print("Single Quote: \'")
print("Double Quote: \"")
print("Carriage Return: \r")
print("Vertical Tab: \v")
print("Form Feed: \f")
print("Backspace: \babcd")